// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:ig
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjXwKo087ubiccoU7fIb97zpnP4oivME',
    appId: '1:809511560314:web:d0d393aabf01ef144cc7c3',
    messagingSenderId: '809511560314',
    projectId: 'myprojectfirebase-ee3a4',
    authDomain: 'myprojectfirebase-ee3a4.firebaseapp.com',
    storageBucket: 'myprojectfirebase-ee3a4.firebasestorage.app',
    measurementId: 'G-9TTZXW9Z2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5p9qUpV-YSVKdZepQgd76LPBtaKhzpBw',
    appId: '1:809511560314:android:6655636293a546bd4cc7c3',
    messagingSenderId: '809511560314',
    projectId: 'myprojectfirebase-ee3a4',
    storageBucket: 'myprojectfirebase-ee3a4.firebasestorage.app',
  );
}
